M48
; DRILL file {KiCad (6.0.0)} date Sat Apr 16 23:03:07 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-16T23:03:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X130.522Y-81.767
X130.522Y-110.867
X170.722Y-81.767
X170.722Y-110.867
T0
M30
